nteract/papermill

papermill/cli.py
papermill/execute.py

This requires me to override the Preprocess.preprocessor method so that I can catch the CellExecutionException. This is a hack that I'd like to eventually remove once notebook execution is more gracefully handled by jupyter_client.

Notebooks should write traceback with cell that failed.

---

papermill/__init__.py
papermill/exceptions.py
papermill/execute.py
tests/test_execute.py

A notebook cell execution error will result in the notebook saving to disk as well as PapermillExcecutionError being raised. The PapermillExecutionError will output both it's own traceback as well as the traceback for the cell that had the exception.

nb cell errors will result in raising a PapermillExecutionError

---

papermill/execute.py

Need to handle cells that don't have outputs when checking for execution errors.

Handle cells without outputs when checking for exec errors.

---

papermill/execute.py

Setting the execution count to "\*" is a violation of the ipynb format and causing bugs in papermill and when trying to open partially complete notebooks in jupyter. The goal of using "\*" was so users could open running notebooks and see what cell papermill was currently running. This PR moves away from the "\*" execution count value in favor of updating a status field in the papermill metadata (i.e. node.metadata.papermill.status). We can then choose down the road how to use the status field for tools like commuter to indicate which cell is being run without violating the notebook spec.

Removing * and replacing with papermill field 'status'

---

papermill/execute.py
tests/test_execute.py

Many users are confused when their notebook fails as to whether it is an issue or with papermill. This "banner" will be rendered whenever there is a notebook generated exception.

Error message at top of notebook if exception encountered.

---

README.rst
papermill/cli.py

- simplify naming (parameters -> param)
- make long and short name of options consistent with leading letter (`--file_param`, `-f`)
- add help options
- change to `src` and `dst` since greater clarity than `notebook` and `output`

Simplify naming of cli options

---

papermill/exceptions.py
setup.py

This removes the color escape chars so that it doesn't muddy up the exception outputs.

using regex to remove ansi escape for colors

---

.coveragerc

The versioneer script comes from [python-versioneer](https://github.com/warner/python-versioneer) which is tested in its own repo. We don't want it to be part of our code coverage.

omit the versioneer script

---

papermill/cli.py
papermill/tests/test_cli.py

Every int is also a float, so checking for float first means we never
create any integers.

[MRG] Swap order of test for `int` and `float`

---

papermill/api.py
papermill/cli.py
papermill/conf.py
papermill/exceptions.py
papermill/execute.py
papermill/iorw.py
papermill/s3.py
papermill/tests/test_cli.py

We ran into an issue where a user had some `!pip install` that had unicode output that wasn't being encoded and decoded properly. This switches the section of code that mixed string concatenation between Python 2 strings and unicode strings over to only using unicode strings. While I was at it I brought in `unicode_literals` from `__future__`.
/cc @mpacer @charsmith

rely on __future__'s unicode_literals

---

papermill/tests/test_api.py
requirements-dev.txt

This adds 2 tests: One for the `display` function and another for initializing a Notebook with a path but no node specified.

Add test for display function

---

papermill/__init__.py
papermill/api.py
papermill/cli.py
papermill/execute.py
papermill/iorw.py
papermill/tests/test_api.py
papermill/tests/test_execute.py

Relative imports force everything to load locally and protects from accidental bad import patterns.

Changed import paths to be relative; rather than a mix of relative and absolute

---

papermill/api.py
papermill/tests/test_api.py

Closes #80
It looks like tuples were used erroneously with the `raw` argument _or_ IPython changed the signature. Regardless, this fixes up the current usage to be more explicit where necessary while cutting down on the extra tuples.
/cc @harph @charsmith

rely on explicit raw arguments

---

papermill/execute.py
papermill/tests/test_execute.py

The large number of backslashes are to escape the escaped strings within the test definitions. Tested each locally that print(foo) displays the correct number of `\` characters for these tests.

Added backslash escaping to prevent python parse errors on notebook execution with errant backslashes

---

papermill/execute.py
papermill/tests/test_execute.py

Passing a json object will give you a dict in your Python notebook instead of a string. Same for lists, numbers, and booleans. This makes passing complex parameters very nice for consumption in the notebook.
Broken out from https://github.com/nteract/papermill/pull/88

Added python type preservation in parameter passing

---

papermill/execute.py
papermill/tests/test_execute.py

Passing a json object will give you a named list in your R notebook instead of a string. Same for lists, numbers, and booleans. This makes passing complex parameters very nice for consumption in the notebook.
Broken out from https://github.com/nteract/papermill/pull/88

Added r type preservation in parameter passing

---

papermill/execute.py
papermill/tests/test_parameterize.py

Fixes #84
The cell containing the default parameters of a notebook is now tagged
with "default parameters".
WDYT?

[MRG] Add tagging mechanism for default parameters cell

---

papermill/api.py
papermill/tests/test_api.py

objects to be displayed with ip_display (IPython.display.display) are in argument list not keywords.
data= does not work on the latest ipython
Spec fix included from original PR: https://github.com/nteract/papermill/pull/112

Display args fix

---

papermill/api.py

objects to be displayed with ip_display (IPython.display.display) are in argument list not keywords.
The suggested changes are to remove the keyword argument "data=" and pass the objects as first argument.
(note that the data= does not work on the latest ipython)

ip_display with list arguments

---

papermill/s3.py

In Python 3, the following:
`
decoded = (undecoded + s).decode(encoding)
`
will result in a TypeError: must be str, not bytes because s is of type bytes and undecoded is of type string.
The suggested PR will fix this issue.

string + string (not string + bytes)

---

papermill/execute.py

This could / should be a configurable -- I mostly need this for slow to start Spark backed kernels.

Increase startup_timeout for execute preprocessor

---

.gitignore
papermill/cli.py
papermill/execute.py
papermill/tests/test_cli.py
papermill/tests/test_execute.py

For a special kernel we use the startup time is substantially longer than 60 seconds and we want to be able to parameterize that value.

Parameterized start_timeout for kernel

---

papermill/tests/test_s3.py
requirements-dev.txt

(sorry for the delay - just got back from vacation).
This is to address issue #117 
The test coverage is admittedly very limited, and it is for 2 reasons:
1. It looks like the s3.py was coded to handle use cases beyond what iorw.py requires. For instance: the ability to read from an archive/compressed file. Yet there are use cases I don't really understand. For example, while "bucket" is a concept defined by the S3 service, the class "Bucket" can be associated with other services (e.g. SQS or EC2). That makes little sense to me, but I'm not claiming I fully understand the original intent.
2. As discussed before, I suggest that the s3.py be scrapped and replaced with a third-party module such as s3fs (which does a good job in providing a python file API on top of S3/boto3)
Therefore …

Add test for s3 back-end (read, write, listdir) using moto lib.

---

papermill/execute.py
papermill/tests/test_execute.py

In locked down environments, markdown no longer runs html inline. This switches the error message cell from markdown to HTML. Additionally, the code is hidden so it appears just as HTML output.

switch to html output error message

---

papermill/cli.py

Set click `disable_unicode_literals_warning=True` to disable unicode literals warning.
As Click (docs)[http://click.pocoo.org/5/python3/#unicode-literals] mentions, in order to continue using `unicode_literals` and ignore the warnings about it, `disable_unicode_literals_warning` must be set to `True`.

Set click disable_unicode_literals_warning=True

---

papermill/iorw.py
papermill/tests/test_iorw.py

When handlers schemas overlapped in pattern matching the handler picking was non-deterministic. This preserves handler ordering and allows for existing handlers to be removed.
Also changed the class to no longer carry global state about handlers on the class.

Made PapermillIO preserve handler ordering

---

requirements-dev.txt
setup.py

This adds extras_require to the setup.py and updates the dependency to be more targeted at notebook (not the jupyter metapackage that is less clear from a dependency perspective what it is doing).

Extras require

---

.travis.yml
requirements.txt
setup.py

This modifies our `requirements.txt` to require `ipython>=5.0` without specifying a Python version. It also makes it such that when a user attempts to install papermill with pip <9.0.1, this will ask them to install pip >= 9.0.1, while explaining that this is a requirement of papermill.
This solution allows us to use IPython's solution for determining whether it should be version 5.x vs version 6+. 
**Note**:  IPython 7.0 will be Python 3.4+ compatible (dropping support for 3.3), and our current approach gets more complicated each time a new compatibility change is released. Instead, I suggest we rely on IPython to do the right thing for IPython.
Additionally, this solution allows us to have a more useful error message if someone is using too old a version of pip to install papermill. It …

Version fix with pip

---

papermill/execute.py
papermill/preprocess.py

This allows it to be used from both preprocess and execute.
Fixes errors like
```
NameError: global name 'log_outputs' is not defined
```

move log_outputs to preprocess

---

setup.py

Small fix for correctness, right now there was a carry-over line from the IPython solution to this that no longer applied (`error` is not in our namespace). It was being caught by `except Exception` which we should also then consider getting rid of or otherwise raising.
@MSeal

remove print statement that raises a NameError and then swallows it

---

.travis.yml

One quick integration test. It would be better to set up a virtualenv at the very end here (doing the right thing for Python2 vs Python3), this does at least verify that the `setup.py` runs in place within a distributed wheel.

verify that the wheel can be installed

---

.travis.yml
MANIFEST.in

In order to avoid manifest errors like those making 0.13.2 and 0.13.3 uninstallable via sdist, we should be making our sdists mirror our vcs. `check-manifest` does this for us. 
The MANIFEST.in changes were based on what it would complain about. 
Note: the `.keep` inclusion is necessary so that git sees the directory and is the convention we should follow elsewhere in the package for consistency.

Check manifest

---

papermill/iorw.py
papermill/tests/test_iorw.py

Discovered that setting an output path to an invalid location did not raise an error in papermill execution.

Made http handler raise_for_status

---

papermill/cli.py
papermill/execute.py
papermill/iorw.py
papermill/tests/notebooks/report_mode_test.ipynb
papermill/tests/test_cli.py
papermill/tests/test_execute.py

Have made an attempt. Please tell me what to change/add. Thanks!

Add option for hiding input

---

README.rst
papermill/execute.py
papermill/tests/test_parameterize.py

Made execution reuse the injected-parameters cell for repeated calls to the same output notebook
Remake of https://github.com/nteract/papermill/pull/138/files

Changed parameter management to add an injected-parameters cell. 

---

papermill/execute.py
papermill/preprocess.py
papermill/tests/test_execute.py

This changes the order in which we are processing messages when running individual cells. 
Importantly, we are no longer waiting for `execute_reply` which means we can no longer expect all iopub messages to be present when processing them.
While this is a useful simplifying assumption, it means we cannot stream the outputs as they come in (behaviour expected from other front-end notebook contexts).
To address this change in the expectations around the iopub messages, I increased the default iopub_timeout value. We may want to strengthen this and disable iopub timeout errors by default.
Because we don't know what the execution count is until we get the execute reply, we cannot canonically state what output number these cells will have, so we optimistically try to log the streamed messages. …

Stream outputs when logging

---

README.md

@fabric-8 put together a new papermill logo! This updates the README to use it. 😄 
see https://github.com/nteract/logos/pull/13

New Papermill Logo!

---

papermill/execute.py

Noticed that this relies on a behavior of how parameterization of cells works. Swapping the order makes the change a little safer.

Moved report mode settings below parameterization

---

setup.cfg

Closes #176, or maybe doesn't, if linting needs a touch up too. This only excludes versioneer from coverage, following the [omit docs for coverage](https://coverage.readthedocs.io/en/coverage-4.2/source.html#source).

excludes versioneer from coverage reporting

---

.travis.yml
papermill/adl.py
papermill/s3.py
setup.py

#187 done in alignment with travis-ci/travis-ci#9069
Plus whitespace changes in other files to align with #183
On Python 3.7: ModuleNotFoundError: No module named 'google_compute_engine'
* GCE might not yet support Python 3.7...
* https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/setup.py#L66

Travis CI: Add Python 3.7 to the testing

---

setup.py

Update the metadata which is displayed on pypi.
Do we want to update the email address?
Reminder: Update twine and setuptools prior to cutting the release as recent versions are needed for long description metadata.

update the package metadata for new pypi site

---

requirements.txt

papermill depends on function "_wait_for_reply" which is only available in 5.3 and later, per https://github.com/jupyter/nbconvert/commit/9bd05ffbaefd6b45452cca51fd7ca8964e033c47
not sure if other functions require a newer version.

requirements: bump version for nbconvert

---

papermill/exceptions.py
papermill/iorw.py
papermill/tests/test_iorw.py

@MSeal this addresses the issue of Nicer error when output directory doesn't exist #201
Please review the PR and let me know for any changes. At present I added the exception throwing for local file system. Please let me know if I need to do the same for others as well

throw nice error if directory doesn't exist

---

papermill/execute.py

Currently execute_notebook is hard-coded to print its two messages
to stderr using print. This PR changes this to use the python
logging framework.
First PR so let me know if you want this at all or in a totally different way. Thanks!
P.S. This project is so cool. Thank you for open sourcing it.

 Using logger instead of print statement

---

papermill/iorw.py
papermill/tests/test_iorw.py

Missed this case when reviewing a PR. Ran into it with testing engines.

Fixed local directory saves to not raise exceptions

---

README.md

- If you set AWS_PROFILE, you can specify which
credentials to use for storing results to s3.
Addresses issue #233

Add note on using multiple AWS accounts

---

setup.py

Since I copied `papermill` directly when creating `bookstore`, a missing `s` that @willingc found in https://github.com/nteract/bookstore/pull/1 was also present here. I have now typed more than 234x the characters that this PR introduces.

stick an s in install

---

papermill/engines.py
papermill/tests/test_engines.py

Noticed the import value changed after using nbformat function which rely on ipython. This fixes the issue by preloading the check.

Fixed checks for ipython kernel to run before ipython might be imported by other functions

---

papermill/abs.py
papermill/iorw.py
papermill/tests/test_abs.py
requirements-dev.txt
requirements.txt

Azure blob storage backend are made available using the abs:// prefix. 
Access will be granted using shared access signatures (SAS) (see https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1)
This pull request addresses the issue https://github.com/nteract/papermill/issues/205

Add azure blob storage backend support

---

.travis.yml
MANIFEST.in
papermill/_version.py
papermill/abs.py
papermill/iorw.py
papermill/s3.py
papermill/tests/test_abs.py
papermill/tests/test_s3.py
papermill/tests/test_utils.py
papermill/utils.py
pytest.ini
requirements-dev.txt
versioneer.py

This needs to be merged asap as papermill is broken with recent boto versions. Tested with some basic s3 notebooks on python 2 and 3 beyond the unittests.
Also fixed the moto test breakage so we can unpin botocore and moto.
The lines touched outside of s3 are the result of black / flake passes cleaning up stray lines.
Took the opportunity to strip out all the unused junk in s3.py. This brings out test coverage up to 90% :confetti_ball:

Fixed botocore change break.

---

papermill/abs.py
papermill/tests/test_abs.py

Papermill expects that the read function returns a list of strings, however `AzureBlobStore.read` returns a string and hence reading from azure blob storage fails with:
```
papermill "abs://myaccount.blob.core.windows.net/sascontainer/sasblob.txt?sastoken" hello_world.ipynb
[...]
return "\n".join(lines)
TypeError: can only join an iterable
[...]
```
This pull request will fix this issue. Reading from azure blob storage was tested with Python2 and Python3

Bugfix: AzureBlobStore.read returns a string but papermill expects a list of strings

---

papermill/execute.py

Added functionality to hide ingested parameters in output notebook if executed with `--report-mode`
I don't think it makes sense to show the ingested parameters in the output notebook when using `--report-mode`.  Here is the issue I created. #253

Hiding Ingested Parameters if `--report-mode`

---

papermill/cli.py
papermill/log.py

When papermill is imported, the logging level was automatically being
set to `INFO`. Many Python libraries are chatty at that logging level
which leads to confusing messages when a user executes a Jupyter
notebook that imports `papermill` and also uses another Python library
to perform some task.
Logging will work correctly even if the call to `logging.basicConfig`
is omitted. It will simply log at the default logging level of the
environment.
Libraries in general should not change the logging level of the
environment at the import level, since this confuses users and is
difficult for users to understand what went wrong when they see
messages they don't expect nor, in many cases, understand.
Signed-off-by: Sergey Kizunov <sergey.kizunov@ni.com>

Do not set logging level on import

---

papermill/engines.py
papermill/iorw.py
papermill/tests/test_engines.py
papermill/tests/test_iorw.py
requirements.txt

This PR implements loading of IO handlers via entry points. This allows a third-party developer to implement a handler for papermill and declare it in `setup.py` under entry points.
The aim is to allow an ecosystem of papermill read / write options. This would allow, for example, to write custom papermill publishing methods that integrate with an organisation's infrastructure, or for a third-party hosting service (e.g. [Digital Ocean Spaces](https://www.digitalocean.com/products/spaces/) ). I have had a lot of success writing custom output formats for [RMarkdown](https://rmarkdown.rstudio.com/), and think allowing this for papermill would be a great feature.
The design of this implementation is inspired by `flake8`.
Effectively, what someone could do is define a package like this:
``` …
```

Allow custom handlers via entry points

---

papermill/execute.py
papermill/tests/test_execute.py

Jupyterlab has no 'jupyter' field in cell metadata, so the code was crashing when it tried to run 
`newcell.metadata['jupyter']['source_hidden'] = True`
in report mode. I added 
`newcell.metadata['jupyter'] = newcell.get('jupyter', {})` 
before this line to fix the issue.

Report mode fix for Jupyterlab

---

papermill/cli.py
papermill/execute.py
papermill/tests/test_cli.py
papermill/tests/test_utils.py
papermill/utils.py

This adds support for executing a notebook in a different working directory. This seems nicer than having to do `(cd some/where && papermill input.ipynb out.ipynb)` or `os.chdir('some/where')` before calling `pm.execute_notebook()`.
It lets you run `papermill --cwd some/where input.ipynb out.ipynb`. `cwd` seems a bit weird as name but it is what Python's `subprocess` uses to name the argument to set the current working directory for new processes so I stuck with it.
Generally useful? If yes I'll add tests.
Created as part of work for https://www.colorado.edu/earthlab/ 🎉

Add support for executing notebooks in a different directory

---

CONTRIBUTING.md

- I believe line 28 should activate `dev`, since that's the env we created on the previous line
- line 38 should use quotes so the shell doesn't expand the square brackets

Fix install instructions

---

papermill/adl.py
papermill/tests/test_adl.py

Calling listdir on the ADL handler with a path such as `adl://my_store.azuredatalakestore.net/path/to/directory` would previously return a list of paths without the `adl://my_store.azuredatalakestore.net/` prefix. Example: `["path/to/directory/foo", "path/to/directory/bar"]`
This would cause problems when the paths were later fed back to PapermillIO (for example, when reading the listed files), as they would be assumed to be local paths and the LocalHandler would be used.
Calling read_notebooks with an adl:// path sufficed to reproduce the issue.
With this PR, the paths returned by the ADL handler are full paths, with the adl:// scheme and store name.

fix adl handler listdir not including adl:// scheme in returned paths

---

papermill/engines.py
papermill/tests/test_engines.py

Closes \#270.
I'm not sure I understand what the current intended behavior for `log_output` is but I think that I preserved it...?

Use tqdm.auto for progress bar

---

requirements.txt

per #287 - tqdm.auto didn't exist in 4.19.4, and perhaps later versions, but it does in 4.29.1.
thx @betatim for [suggestion](https://twitter.com/betatim/status/1087020834827522048) to go the extra inch :)

update requirements.txt to pin tqdm version >= 4.29.1

---

papermill/iorw.py
papermill/tests/test_gcs.py
requirements-dev.txt
requirements.txt

Fixes #213. This looks like all that's needed but I'm not sure what to do about testing. It seems like the S3/Azure functionality is all basically implementing stuff that's already part of `gcsfs`, hence the simplicity of this logic; I'm not sure that tests like those in `test_s3` and `test_abs` would really be doing anything...

Add GCS handler

---

tox.ini

Should be merged after #292.
Docs can now be built locally by entering `tox -e docs`.

add tox doc build to ease local doc builds

---

papermill/tests/test_translators.py
papermill/translators.py

This PR adds `None` translation method to `Translator` class.
When I try to pass `None` through papermill,
it's translated into `"None"` string object because `translate_escaped_str` method is called.
I think that `None` should be translated into `None` in Python notebook.

Add None translation

---

README.md
papermill/iorw.py

- Update README.md to include supported name handlers.
- Minor cleanup in iorw.py to conform to previous style during instantiation of PapermillIO.

Update README.md to include supported Handlers. Minor iorw cleanup

---

papermill/iorw.py
papermill/tests/test_gcs.py
requirements.txt

Add retry library to be able to handle writes to GCS.
Currently papermill emits a save after each cell executes.

Handle 429 Errors

---

papermill/iorw.py
papermill/tests/test_gcs.py
requirements.txt

The retry library is no longer being maintained, and is causing issues with conda builds. This should help unblock https://github.com/conda-forge/papermill-feedstock/pull/11

Replaced retry with tenacity library

---

binder/postBuild
binder/requirements.txt

Fixes https://github.com/nteract/papermill/issues/348
Tested against my branch at https://hub.mybinder.org/user/mseal-papermill-4d7pfjpg/notebooks/binder/cli-simple/cli_example.ipynb
See https://github.com/pypa/pip/issues/6433 for why this caused us problem with pip 19 upgrade.

Added postBuild to fix pip install issues with pip 19

---

.gitignore
binder/requirements.txt
requirements.txt

- remove unused pandas dependency (leftover from 0.* versions)
- add .vs/ to .gitignore
* added pandas to binder requirements as it's referenced in a notebook even though it will be brought in as scrapbook dependency

remove unused pandas dependency

---

papermill/engines.py
papermill/execute.py
papermill/tests/test_engines.py
papermill/tests/test_execute.py

Allow user to pass notebook engine arguments via kwargs on pm.execute_notebook()
Right now there is no way (*I could find) to pass args like allow_errors and timeout

pass through notebook engine arguments

---

papermill/cli.py
papermill/iorw.py
papermill/tests/parameters/example.yaml
papermill/tests/test_cli.py

Fixes  #345
Right now the YAML load is parsing strings into datetime objects, which causes an error
for JSON serialization. This will prevent that parsing and keep them as strings.

Don't auto-convert to datetimes when parsing YAML

---

CONTRIBUTING.md

An additional flag is required for pip 19 to do the editable install
because papermill has a pyproject.toml file.

Update CONTRIBUTING.md for pip 19

---

.gitignore

Noticed the `pip-wheel-metadata` directory get generated with an up to date pip, cluttering up the git repo locally. Now we can ignore it.

git ignore pip-wheel-metadata directory

---

papermill/engines.py
requirements-dev.txt
requirements.txt
setup.py
tox.ini

This saves substantially on initial load times for papermill, and reduces initial execution latency if progress bars are turned off.

Moves imports to be lazy which pull in IPython

---

docs/usage-parameterize.rst

Adds explanation to documentation on how to create the tags for both Jupyter Notebook and JupyterLab:

Adds explanation on how to parameterize. Closes #386

---

requirements-dev.txt

Adds [recommonmark](https://github.com/rtfd/recommonmark) dependency to [`requirements-dev.txt`](https://github.com/nteract/papermill/blob/master/requirements-dev.txt). Requested and referenced in #388 right [here](https://github.com/nteract/papermill/issues/386#issuecomment-506017765).

Adds recommonmark dependency for building sphinx docs

---

CONTRIBUTING.md

Adds guidelines on how to contribute more easily to documentation. 
Requested on #388 right [here](https://github.com/nteract/papermill/issues/386#issuecomment-505940465). 
File edited: [`CONTRIBUTING.MD`](https://github.com/nteract/papermill/blob/master/CONTRIBUTING.md)
The section added contains:
- how to generate docs
- a bit about what they use to be generated
- how to run tests on them

Adds guidelines for contributing and generating documentation

---

papermill/engines.py
requirements.txt

- lock-triggered `OSError`s were fixed
+ tqdm/tqdm/issues/611 -> tqdm/tqdm/pull/617
+ tqdm/tqdm/issues/466 -> tqdm/tqdm/pull/698
- specify that the progressbar is about cell execution

update tqdm version and usage

---

docs/usage-execute.rst
papermill/cli.py
papermill/tests/test_cli.py

Hello!
This PR handles #363 
```
papermill input.ipynb output.ipynb -p my_list abc def ghi
```
But, it arguably relies on hacking `click.Option`, and `click` authors seem to be against variadic options [1].
Full credit goes to user stephen-rauch on stackoverflow [2]
The `class OptionEatAll` should probably be placed somewhere better...
[1] https://github.com/pallets/click/pull/259
[2] https://stackoverflow.com/a/48394004

list parameter

---

papermill/cli.py
papermill/engines.py
papermill/execute.py
papermill/preprocess.py
papermill/tests/__init__.py
papermill/tests/test_cli.py
papermill/tests/test_engines.py
papermill/tests/test_execute.py
papermill/tests/test_preprocessor.py
tox.ini

This complements the existing log_output option to make it possible to more directly stream the notebook's stdout/stderr messages into separate files, without Papermill's internal log messages interfering.
Conveniently, `--stdout-file /dev/stdout --stderr-file /dev/stderr` lets one connect the two streams directly to their respective files.
All that is implemented in the last commit – there's a bunch of smaller preparatory commits that made it more convenient to develop this.

Add stdout-file/stderr-file options

---

papermill/tests/test_cli.py

These two tests only basically test that `click` actually passes values through.
I think they might have been some vestigial experiment code.

Remove CLI tests that don't actually test the CLI

---

docs/usage-execute.rst
papermill/cli.py
papermill/tests/test_cli.py

This reverts commit 30c8ad1596a4850fea77d9a1cb3cba13e8a279c5.
@gshiba I found a fix for #417 but in in making that fix I discovered that there's no sane way to avoid capturing the notebook path when the last argument before the notebook input/outputs is a `-p`. We can't tell the `-p` option how many arguements there are and there's no way to detect if the notebook path is meant to be an additional list argument or a notebook path. The handler for notebook paths is definable by external users and has a wide range of acceptable values, so checking if the path is a notebook during option parsing is challenging to the point of impossibility for all use-cases.
See #427's example:
`papermill -p foo bar papermill/tests/notebooks/simple_execute.ipynb /tmp/out.ipynb`
After giving this some thought …

Revert "list parameter (#411)"

---

papermill/iorw.py
papermill/tests/test_iorw.py

This implements the change suggested by @MSeal at #420.
I confirm that this solves the original issue with my notebook, as well as the one with `echo 'import world_bank_data as wb; wb.get_countries()' | jupytext --from py --to ipynb --set-kernel - | papermill > out.ipynb`.
@MSeal , I had to modify the test `test_write_stdout`. It is expected that I had to mock `stdout` with `io.BytesIO` instead of `io.StringIO`?

Explicit utf-8 encoding on stdout

---

DEVELOPMENT_GUIDE.md
docs/_templates/page.html
docs/extending-developing.rst

This PR addresses a few typos I found in the documentation.

Fix typos in documentation.

---

papermill/iorw.py

Closes #439 
Modifies `NoDatesSafeLoader` to inherit from `yaml.SafeLoader`, so that the base class `yaml.SafeLoader` is not modified and the default behaviour of the pyyaml module is unchanged.

Fix custom yaml loader

---

papermill/tests/test_translators.py
papermill/translators.py

Discussed this some off-line about approaches, but essentially passing `-p _foo bar` to papermill (common for system parameters you don't want namespace collisions on) breaks R kernel executions. To avoid this the PR strips leading `_` characters from parameter assignments.

Fixed crashing R kernels with common illegal variable name

---

papermill/tests/test_translators.py
papermill/translators.py
requirements-azure.txt

Translator for the recently-released .net-csharp kernel. 
- Dotnet core 3.0 and 2.1 (https://dotnet.microsoft.com/download) 
- "Dotnet try" tool (https://www.nuget.org/packages/dotnet-try/) 
`dotnet tool install --global dotnet-try`
- .net kernels for Jupyter
`dotnet try jupyter install`
(See https://www.hanselman.com/blog/AnnouncingNETJupyterNotebooks.aspx )
I had to lock the `azure-storage-blob` reference to the mid-2019 version, which is still supported. The Azure Python SDK was updated in late October with breaking changes. 
I didn't implement "None," although I think it might be possible to do something clever with `Nullable`s.
I implemented List as an array and Dict as a Dictionary<Object,Object?>. I could make them more consistent by making List `List<Object>` but that seems YAGNI.

Translator for C# (.net-csharp) kernel

---

papermill/execute.py
papermill/tests/notebooks/sysexit.ipynb
papermill/tests/notebooks/sysexit0.ipynb
papermill/tests/notebooks/sysexit1.ipynb
papermill/tests/test_execute.py

Hi!
I'm a newbie around these parts (and contributing to open source in general!) but thought I might make an attempt to resolve #435 . Noticed that without arguments to exit() or with None, `evalue` returns an empty string; that should also be evaluated the same as 0 I imagine? Any and all feedback is welcome 🙏🏾
Thank you!
Yusuph

Ending notebook execution early with sys.exit without raising an exception

---

papermill/engines.py
papermill/tests/notebooks/simple_execute.ipynb
papermill/tests/test_engines.py

Found we were making notebook outputs that sometimes didn't validate against nbformat schemas. This fix should correct that issue on markdown and raw cell types.

Fixed metadata writing on markdown and raw cells to follow v4 schema

---

papermill/translators.py
requirements-dev.txt
requirements.txt

Resolves #436.
I picked cutoff values for when to use newlines/indents based on my own practices. Was thinking of trying to limit line length, but we don't know the variable name so we can't calculate the full line length.

Use Black to format Python parameters for versions >= 3.6

---

docs/reference/papermill-cli.rst
docs/usage-cli.rst
papermill/cli.py
papermill/tests/test_cli.py

This updates the CLI docs to include the full output of `--help` after
this patch; it seems that some flags have been added without
regenerating it, so the diff includes more than just this new
`--execution_timeout` flag.

Add --execution_timeout flag for failing on too-slow cells

---

papermill/execute.py
papermill/tests/test_execute.py

Markdown is (mostly) a superset of HTML, meaning there's a lot of HTML one can include directly as markdown content. Papermill can use this to have a slightly cleaner error alert at the top of a failed notebook, by not having both code and output, just output only.
This makes the rendering of a broken notebook (such as `papermill/tests/notebooks/broken.ipynb`) cleaner in an interactive Jupyter instance, as well as on the GitHub and NBViewer static renderers:
Before:
- <https://gist.github.com/huonw/b08434842b6b9f6d45090141ae4327dd>
- <https://nbviewer.jupyter.org/gist/huonw/b08434842b6b9f6d45090141ae4327dd>
After:
- <https://gist.github.com/huonw/f22a6caf6bf8c31538000b88e28c05da>
- <https://nbviewer.jupyter.org/gist/huonw/f22a6caf6bf8c31538000b88e28c05da>

Use a markdown cell for error flagging, prettier than %%html

---

papermill/tests/test_adl.py
pytest.ini

- Ignore deprecated warning module
- Update assertEquals to assertEqual
For #228

Fix warnings in pytest

---

papermill/exceptions.py
papermill/execute.py
papermill/tests/notebooks/broken1.ipynb
papermill/tests/test_execute.py

Papermill currently inserts an error message `An Exception was encountered at 'In [NNN]'` at the top of a notebook that fails to execute, where NNN is the cell execution count of the failing cell. This patch adjusts the `In [NNN]` text to be a link to the relevant cell, to make it easy to jump to. This works by inserting another markdown cell immediately before the failing cell, where the markdown cell contains an HTML anchor (specifically, `id="papermill-error-cell"`). The heading then links to it with a `#papermill-error-cell` fragment HREF.
This helps reduce the scrolling and searching required for long notebooks where the error cell might be one of dozens, or hidden among long output. For an example of the latter, see <https://nbviewer.jupyter.org/gist/huonw/dd13fa49b5876bfea26b6983270 …

Include link to the cell with an error, in failure heading

---

.travis.yml
azure-pipelines.yml
papermill/clientwrap.py

Added guard for asyncio registration for python 38 on windows

---

papermill/parameterize.py
papermill/tests/test_parameterize.py
papermill/translators.py

Related to #520.
Opening PR to discuss changes.
Added a "comment" parameter to the codify function, with a "Parameters" default value.
Exposed via the `parametrize_notebook` function.
Comments @MSeal?

adding "comment" parameter for custom comment in injected cell

---

requirements.txt

As previously raised in #486 #492 #500 #522 and #523 if papermill is used in an environment with an older version of `jupyter_client` it will throw an error. This is caused by the dependency `nbclient>=0.2.0` that depends on `jupyter_client>=6.1.0`.
This dependency is overridden by papermill by having `jupyter_client` in `requirements.txt` without a version, meaning any version (even an older one) is accepted if already installed. To make sure the expected version of `jupyter_client` is installed we should set `jupyter_client>=6.1.0` to match `nbclient`.
Fixes #526

Set jupyter_client version in requirements.txt

---

docs/usage-cli.rst
docs/usage-inspect.rst
docs/usage-workflow.rst
papermill/__init__.py
papermill/cli.py
papermill/execute.py
papermill/inspection.py
papermill/iorw.py
papermill/models.py
papermill/parameterize.py
papermill/tests/notebooks/complex_parameters.ipynb
papermill/tests/notebooks/notimplemented_translator.ipynb
papermill/tests/test_cli.py
papermill/tests/test_inspect.py
papermill/tests/test_translators.py
papermill/tests/test_utils.py
papermill/translators.py
papermill/utils.py
requirements-dev.txt

This is a reboot of #158 
It adds a new option `--help-notebook` to create a new cli usage:
```
papermill --help-notebook input_notebook.ipynb
```
Due to that I had to remove the `required` statement on OUTPUT_PATH. But the test is still done within the `papermill` function to keep the behavior if `--help-notebook` is not set.
Fixes #225 => in particular the default parameters resulting of the code introspection are added as a dictionary in metadata `nb.metadata['papermill']['default_parameters']`.
For now this add the ability for Python. I'm not familiar to the other languages to build the proper regex.
> Note: I use a regex instead of `ast` for Python for two reasons: `ast` removes all comments but I use them to get a help comment. ast parsing for non-python language won't be available. …

Guess params by introspecting the _parameters_ cell

---

papermill/execute.py
papermill/inspection.py
papermill/tests/test_execute.py
papermill/tests/test_inspect.py

Convert `Path` to `str` when received. Fixes #543.

Allow `pathlib.Path` paths

---

papermill/cli.py
papermill/tests/test_cli.py

Fix #558 
Prevent `TypeError: 'NoneType' object is not iterable` exception when using empty (or with comments only) YAML file in CLI
Based on changes suggested by @dhorgan.
```
...
parameters_final.update(yaml.load(base64.b64decode(params), Loader=NoDatesSafeLoader) or {})
...
parameters_final.update(read_yaml_file(files) or {})
...
parameters_final.update(yaml.load(params, Loader=NoDatesSafeLoader) or {})
...
```
Also add single test `test_parameters_empty` in `test_cli.py` instead of creating a separate test for "-f", "-y" and "-b"

Support empty YAML configuration 

---

papermill/iorw.py
papermill/tests/notebooks/nb_version_4.4.ipynb
papermill/tests/test_execute.py

Fix issue #568.
An upgrade is performed after loading the notebook, so Papermill should always work internally with a notebook with the latest version.

Fix #568 (unexpected id field)

---

papermill/translators.py

The jupyter [sparkmagic](https://github.com/jupyter-incubator/sparkmagic) project defines a kernel named `pysparkkernel` that can be interpreted by `papermill` using the `PythonTranslator`
This PR registers the `PythonTranslator` for `pysparkkernel` kernels

Register PythonTranslator for pysparkkernel kernels

---

papermill/translators.py

Added the optional comment parameter to the codify function in MatlabTranslator, like it has been in Translator and PythonTranslator before.
This should fix the issue reported in #572.

Add optional comment parameter to MatlabTranslator's codify

---

papermill/cli.py
papermill/execute.py
papermill/parameterize.py
papermill/tests/notebooks/blank-vscode.ipynb
papermill/tests/test_cli.py
papermill/tests/test_execute.py
papermill/tests/test_s3.py
papermill/utils.py

Resolves https://github.com/nteract/papermill/issues/581
Adds a language option to the CLI to overwrite the notebook language (or supply one if a file was invalid / not parsing correctly).
Fixes the language fetch from the document to first look in the v4 path, than the v3 path for the notebook language. Apparently every tool was publishing to both places except VSCode which only uses the v4 location and we never caught it before.

Added language field and fixed language fetch for v4 spec

---

requirements.txt

https://github.com/nteract/papermill/blob/main/papermill/translators.py#L191  relies on `FileMode` to include a `string_normalization` parameter. This was introduced in 
https://github.com/psf/black/commit/36d3c516d3c09fc5f05c420900dd6b854e3c8bbd#diff-fe0a71b8c720ce9ae962aaa7a1bdc63f30bc8eff585cf25e466cd33306c5a042R108. Explicitly setting this constraint would avoid unnecessary troubleshooting.

Set minimum version for black

---

papermill/s3.py
papermill/tests/test_s3.py

Breaks out of the read loop in s3 cat function to avoid [RFC2616#14.35.1](https://datatracker.ietf.org/doc/html/rfc2616#section-14.35.1).
Fixes #603

Updated file read to not fail early with a boto empty file exception

---

papermill/iorw.py

_Addressing commonly seen warning in iorw.py file._
```
/usr/local/lib/python3.7/dist-packages/papermill/iorw.py:50: FutureWarning: pyarrow.HadoopFileSystem is deprecated as of 2.0.0, please use pyarrow.fs.HadoopFileSystem instead.
from pyarrow import HadoopFileSystem
```
Fixes #600

Removing deprecated pyarrow.hdfs.connect call from iorw.py

---

papermill/iorw.py

`papermill foobar.ipynb foobar.ipynb.out` gives me the followings:
```
papermill/iorw.py:126: UserWarning: The specified input file (foobar.ipynb.out) does not end in one of ['.ipynb', '.json']
"The specified input file ({}) does not end in one of {}".format(path, extensions)
```
Which led me think it took the output path as input file.

fix(iorw.py): misleading output message

---

papermill/engines.py
papermill/tests/notebooks/simple_execute.ipynb
papermill/tests/test_engines.py

Added possibility to set description of cells that will be injected to the tqdm.
To add description to a specific cell the user must add a string with this formatting in the desired cell:
`# papermill_description=description_of_cell`
When the execution will reach that cell, the description of the tqdm will be changed from `Executing x:` to `Executing description_of_cell`. 
If no cell contains the tag `papermill_description=`, the execution will be as before the implementation of this functionality.
If a cell containing the description tag is followed by cells that don't have the tag, the tqdm description is set to the last valid description.
I decided to implement this functionality because I think it is pretty useful with long notebooks that have very slow cells (i.e. data preparation …

Added cell description to tqdm

---

papermill/abs.py
papermill/tests/test_abs.py

Corrected Azure Blob URI regex matching if the blob include some prefix

---

papermill/iorw.py
papermill/tests/test_hdfs.py
requirements/hdfs.txt

Fixes #657 
I fix HDFSHandler to match PyArrow.fs.HadoopFileSystem API.
As stated the reasons in #657, I removed `import PyArrow.HadoopFileSystm` and updated `requirements/hdfs.txt`.

fix(iorw.py): update HDFSHandler to adapt PyArrow.fs.HadoopFileSystem API

---

docs/requirements.txt
papermill/tests/test_autosave.py
papermill/tests/test_cli.py
papermill/tests/test_clientwrap.py
papermill/tests/test_engines.py
papermill/tests/test_execute.py
papermill/tests/test_gcs.py
requirements/dev.txt

Changed to use `unittest.mock` instead of `mock`.
- Supported versions of Python have `unittest` as a standard library,
- Unnecessary dependencies can be removed.
Fixes #659

use unittest.mock instead of mock

---

papermill/execute.py
papermill/iorw.py
papermill/parameterize.py
papermill/tests/test_execute.py
papermill/tests/test_iorw.py
papermill/tests/test_parameterize.py

In the current setup of papermill, an `output_path` is required to write an output ipynb file even if you only want to use the returned `NotebookNode` object. For example, in my case, I end up using `tempfile` a good amount to get around this.
This motivation came up in PR https://github.com/nteract/papermill/pull/107, as well
Let user pass `output_path = None` to indicate they don't want to write an output ipynb.
A new IO handler was added, `NoIOHandler` to deal with this option.
I tried to match the api interface of PR https://github.com/nteract/papermill/pull/107, but I could also see having a specific string that indicates no output writing (similar to `"-"` indicating stdin/stdout).
The advantage being that the IO handler can be registered in the IO factory as designed, and not …

Option for not writing an output ipynb file

---

papermill/engines.py
papermill/execute.py
papermill/parameterize.py
papermill/tests/test_execute.py

At Noteable, we came across a use-case where parametrized executions with a [custom Noteable engine](https://github.com/noteable-io/papermill-origami) were not working because papermill expects the `kernel_name` to be present in the `kernelspec` of the notebook if `kernel_name` was not explicitly passed in as a kwarg. It throws a `ValueError` with the message "No kernel name found in notebook and no override provided.". Like so,
```
>>> pm.execute_notebook(
f'noteable://{file_id}', 
'foo.ipynb', 
engine_name='noteable'
file=file, 
client=client, 
log_output=True,
)
...
ValueError: No kernel name found in notebook and no override provided.
```
This PR allows the extended engine to define custom business logic for the following:
- fetching kernel name from the notebook object by …

Allow custom implementations of `nb_kernel_name`  and `nb_language` in papermill engines

---

papermill/execute.py
papermill/iorw.py
papermill/parameterize.py
papermill/tests/notebooks/test_notebooknode_io.ipynb
papermill/tests/test_execute.py
papermill/tests/test_iorw.py
papermill/tests/test_parameterize.py

User can pass an in-memory `nbformat.NotebookNode` object to `pm.execute_notebook` instead of requiring a path.
Related to issue https://github.com/nteract/papermill/issues/444
This adds a `NotebookNodeHandler` to read the input object.
A bit of refactoring was also needed to move code that expected a string:
- Stdin/Stdout was pulled out into its own handler
- The check and warning for `.ipynb` and `.json` file extensions by `PapermillIO` read/write was moved into `get_handler` (this also made the code more DRY)
Happy to take feedback, thanks!

Adds input of NotebookNode object directly

---

papermill/execute.py
papermill/parameterize.py

This PR removes the `nb = copy.deepcopy(nb)` steps inside parameterize.py and execute.py. This does not fix any tracked issue I know of. What this PR solves are some issues and annoyances surrounding the deepcopy (and pickle) standard libraries.
```python
nb = copy.deepcopy(nb)
```
Currently, notebooks that contain cells or parameters with objects without a \_\_dict\_\_ require some heavy object/class patching of their magic methods. Also, anything that is unable to be serialized with pickle will run into issues here as well. Removing all of the `copy.deepcopy(nb)` calls fixes this issue.
The removal of these can be done safely because the deepcopy currently has no useful behavior; just looking at the code surrounding these calls makes it somewhat apparent. All tests are currently passing …

Remove deepcopy steps during parameterize_notebook.

---

papermill/tests/test_exceptions.py
papermill/tests/test_utils.py

This pull request fixes multiple failing tests within test_exceptions.py and test_utils.py when papermill is run on the windows platform. 
test_exceptions.py : test_exceptions_are_unpickleable
The previous behavior of the code created a temporary file with the incorrect permissions assigned to it resulting in a PermissionDenied error.
test_utils.py : test_chdir
The previous behavior of the code used os.path to compare against strings, which had the issue of sometimes comparing minified path strings (such as 'C:\\Users\\USER~1\\Path\\To\\My\\Basement') to non-minified path strings. New code uses more commonly used pathlib library to get and compare Paths.

2 failing test fixes for Windows platform

---

papermill/tests/test_translators.py
papermill/translators.py

Thanks for papermill! I have used it for python notebooks, but a lot of my work is best done in shell, for which I use jupyter notebooks with the [bash_kernel](https://github.com/takluyver/bash_kernel/) (via *.sh scripts and jupytext). 
Alas papermill doesn't seem to support bash/shell script, due to a hitherto unimplemented bash translator. This PR implements a `BashTranslator`, and therefore enables bash kernel notebooks to be parametrised.  This code supports `str`, `list`, `bool`[^1], `None`, `int`, and `float` parameter values. Dict could in theory be supported via [associative arrays](https://linuxhint.com/associative_arrays_bash_examples/) but for now they are not implemented[^2].
For a functioning example, please see the attached notebook.
Best,
K
[^1]: Bash doesn't really have a …

Implement bash translator

---

requirements.txt

Requires a minimum version of `tenacity`.
In version `5.0.1` and below of `tenacity`, the `wait_exponential` method does not take a kwarg of `min`.
https://github.com/jd/tenacity/blob/5.0.1/tenacity/wait.py#L136-L152. This was resolved in the following version `5.0.2`.
However, `papermill` references this kwarg here: https://github.com/nteract/papermill/blob/main/papermill/iorw.py#L330-L333. To ensure proper dependency resolution, the resolved `tenacity` version should be at least `5.0.2` for this particular code to execute successfully.

Add Minimum Version of Tenacity For Resolution

---

papermill/exceptions.py
requirements.txt

Removes use of ansiwrap in the package for the reasons in #680

Remove use of ansiwrap

---

.github/dependabot.yml

This will help to keep the CI/CD updated.
Dependable is a GitHub application that, based on config checks if some GitHub action can be updated to the latest version if yes, it will create a PR with this update some it will also verify that the update still works with the repository...
See for example here: https://github.com/Borda/docker_sample/pulls?q=is%3Apr+is%3Aclosed+author%3Aapp%2Fdependabot

add dependabot for GHA

---

papermill/execute.py
papermill/parameterize.py

Always upgrade the Notebook to the latest v4 before writing new cells into it. This prevents *e.g.* having a malformed Notebook with a mix of `v4.4` cells with `v4.5` cells.
Fixes #686

Always upgrade the Notebook before writing into it

---

docs/usage-inspect.rst
setup.py

When not specifically referring to the [`parametrize` package](https://pypi.org/project/parametrize/), this PR ensures the standard spelling “parameterize” is used throughout the documentation and metadata.
This is consistent with the GitHub project page summary and with the first sentence of README.md.
Fixes **(no issue filed)**

Use “parameterize” spelling

---

papermill/abs.py
papermill/tests/test_abs.py
requirements/azure.txt

It allows abs:// to be used without a sas token. In this case it will fall back on[ Azure identities Environment credentials](https://learn.microsoft.com/en-us/python/api/azure-identity/azure.identity.environmentcredential?view=azure-python). This allows you to use a service principle for authentication with azure.
Changes:
abs.py changed the regex
abs.py added a default for when sas token is empty. It will use env creds in this case. 
tests for ABS without a sas token
Dependecies:
azure-identity -- because we will be using EnvironmentCredential from it

ABS add support for using a Service principle via EnvCreds

---

docs/changelog.md
papermill/execute.py
papermill/inspection.py

Reuses the util methods for inspection that require user overrides when critical metadata is missing.
Fixes #735

Changed parameter inspection to reuse utils funcs

---

pyproject.toml

Universal wheels should work on both Python 2 and 3, and Papermill requires Python 3.8+.
Removes the `universal` marker, since the contents of the wheel aren't universal.

Unmark wheel as universal

---

papermill/adl.py
papermill/cli.py
papermill/clientwrap.py
papermill/exceptions.py
papermill/execute.py
papermill/inspection.py
papermill/iorw.py
papermill/s3.py
papermill/tests/test_cli.py
papermill/tests/test_execute.py
papermill/tests/test_s3.py
papermill/translators.py
setup.py

This PR cleans up various uses of `%` or `.format` or ` + ` string interpolation to use f-strings instead, for performance and readability.
Conversion was guided by https://github.com/ikamensh/flynt and hand-checked.

Use f-strings where possible

---

.pre-commit-config.yaml
papermill/adl.py
papermill/cli.py
papermill/exceptions.py
papermill/tests/test_inspect.py
papermill/tests/test_translators.py
papermill/translators.py
pyproject.toml

This PR cleans up the pre-commit configuration slightly:
* Python 3.8 is no longer required to run the tools
* yesqa isn't necessary, since it's depending on flake8 (the use of which was dropped in #752)
* Ruff has rules for Pyupgrade, so it isn't necessary as a separate hook either
Some of the f-string changes the pyupgrade commit does are also done in #762, so these will conflict slightly.
I didn't enable `ruff-format`, since the current quote style in this repository is mixed, and that's not (yet: https://github.com/astral-sh/ruff/issues/9185) supported by Ruff's formatter.

Pre-commit fixes

---

requirements.txt

Upgrading nbformat, as nbformat==5.1.2 and 5.1.3 causes "AttributeError: 'NoneType' object has no attribute 'cells'" due to upgrading nbformat to v4 `nb = nbformat.v4.upgrade(nb)`
Sets nbformat to a minimum version of 5.2.0 to avoid `no attribute 'cells'"`
Fixes #769

Fixes # nbformat to 5.2.0 to cell None type

---

papermill/engines.py

Fixes #777 (Oh, I unintendedly hit the jackpot🎰)
This pull request is an extension that allows passing arguments to `tqdm` by enabling the `progress_bar` parameter of `execute_notebook` to accept a `dict`.
This pull request maintains compatibility with the current implementation, though it might make the conditional branching a bit messy...
I believe there could be discussions on how to actually enable such specification, as follows.
```python
elif isinstance(progress_bar, dict):
_progress_bar = { "unit": "cell", "desc": "Executing" }
_progress_bar.update(progress_bar)
self.pbar = tqdm(total=len(self.nb.cells), **_progress_bar)
```
```python
elif isinstance(progress_bar, dict):
self.pbar = tqdm(total=len(self.nb.cells), **progress_bar)
```
```python
if isinstance(progress_bar, bool):
if …
```

make progrgress_bar param accept a dict

---

papermill/execute.py
papermill/tests/notebooks/line_magic_error.ipynb
papermill/tests/test_execute.py
papermill/tests/test_iorw.py

When notebooks with cell / line magics are executed and if the magic command fails, papermill doesn't throw any exception and returns exit code 0. This is because papermill relies on cell error output to raise PapermillExecutionError.
When magic commands fail, CellExecutionError is still thrown and recorded as cell metadata, and notebook execution stops. However, since these errors don't produce any cell error output, no exception is raised.
Changes in this PR check cell metadata for exceptions recorded by papermill (due to CellExecutionError) in addition to cell error outputs and raise PapermillExecutionError in those cases.
fixes https://github.com/nteract/papermill/issues/501, https://github.com/nteract/papermill/issues/381

raise PapermillExecutionError when CellExecutionError is raised without cell error output

---

papermill/execute.py

this is in addition to https://github.com/nteract/papermill/pull/786 
- fixing overriding regular error type detection. 
- making traceback an empty list instead of empty string

prevent error override, fix traceback type

---

.readthedocs.yaml

RTD builds [haven't succeeded](https://readthedocs.org/projects/papermill/builds/) since docs/requirements.txt was moved in #748, so the latest docs build is for 2.4.0.

[DOC] update path to requirements for readthedocs
