nteract/papermill

.travis.yml
just the beginnings to kick things off
=> create a travis setup

.idea/vcs.xml, .travis.yml, papermill/cli.py, papermill/execute.py, requirements.txt, setup.py, tests/__init__.py, tests/notebooks/test1.ipynb, tests/test_notebooks.py
* added a super simple test
* switched from kwargs to parameters to avoid a conflict between notebook parameters and user namespace
=> fix: avoid collisions with parameters and user namespace

README.rst, papermill/__init__.py, papermill/api.py, setup.py, tests/__init__.py, tests/notebooks/directory/input_1.ipynb, tests/notebooks/directory/input_2.ipynb, tests/test_api.py
All notebook data dict will be returned from pm.fetch_notebook_data(nb) and a collection of notebooks can return a dataframe from pm.fetch_notebooks_dataframe(nbs).
=> fetch data and dataframes

README.rst, papermill/__init__.py, papermill/api.py, tests/test_api.py, tests/test_execute.py
Notebook and NotebookCollection class methods for loading are replaced by regular functions.
=> read_notebook and read_notebooks instead of classmethods.

README.rst, papermill/cli.py, papermill/execute.py, tests/notebooks/result_notebook.ipynb, tests/notebooks/simple_execute.ipynb
preface tag is now parameters tag
=> no more preface

README.rst
=> Link to bindings for recording values

papermill/api.py, papermill/execute.py, papermill/iorw.py
Removing reader and writer customizing framework in favor of monkey patching for now.
=> Removing reader/writer customization

papermill/api.py, papermill/cli.py, papermill/execute.py, papermill/iorw.py
Execute_notebook can read from a file or from a dict.
Moved listing of notebooks into a directory to make it easier to monkey patch just that functionality.
=> Load from yaml

papermill/execute.py
Makes sure to check the passed in kernel name if supplied instead of the nb kernalspec.name before writing parameters.
=> check supplied kernel_name before writing params.

papermill/iorw.py, tests/notebooks/broken.ipynb, tests/notebooks/collection/result1.ipynb, tests/notebooks/collection/result2.ipynb, tests/test_api.py, tests/test_execute.py
Users should only have to specify read, listdir, and write if they are customizing IO. I've also added a decorator to help them with this.
=> introduce papermill_io object for easier customization of io

papermill/api.py, papermill/execute.py, papermill/iorw.py, tests/test_api.py
Writes the notebook as each cell executes to mimic the same functionality as "run all" in the web ui. Also includes timing and success status for each cell. Give this PR a little extra attention since a fair amount about the execution is changing.
=> Live Notebook updates

papermill/execute.py
This fixes #25 and both failing tests.
=> Fixed failing tests

papermill/cli.py, papermill/execute.py, setup.py
Adding progress bar via tqdm. Could use some eyes on how I pass the flag.
=> added progress bar

papermill/cli.py, papermill/execute.py, papermill/tests/notebooks/test_logging.ipynb, papermill/tests/test_execute.py
Users are requesting a flag to let them view text outputs in stderr and stdeout.
=> output logs to stderr and stdout

papermill/execute.py, papermill/iorw.py, papermill/tests/__init__.py, papermill/tests/test_execute.py
Paths to the input and output notebooks will be directed to stdout. A mod to the File System objects allow the customization of how the output gets rendered to links can be supported.
=> Pretty print

papermill/api.py
allow initialization via existing nbformat.Notebook object
=> Api nb from nb

README.rst
Parameter-izing since we're setting parameters, not making our notebook parametric. Closes #59 
Hat tip to @ctb 🎩
=> address word choice for parameter-izing

papermill/iorw.py, setup.py
Added HttpHandler to support inputs and outputs from http(s) endpoints. **Issue:** https://github.com/nteract/papermill/issues/65
=> Added HttpHandler

README.rst, papermill/execute.py, papermill/tests/notebooks/no_parameters.ipynb, papermill/tests/test_execute.py
Also allowed for notebooks with no parameter tags
=> Changed parameters to append cells instead of replace

papermill/execute.py, papermill/tests/test_execute.py
Solves https://github.com/nteract/papermill/issues/66
=> Fixed quote escaping for variable assignment from parameters

README.rst, papermill/tests/notebooks/binder.ipynb, requirements.txt, setup.py
Makes a sample executable code snippet using binder.
=> Added Binder Logo to README

papermill/api.py, setup.py
- clean up parameter passing of tuples in `api.py`
- rename error prone `dfs` and `nbs` to more meaningful collection names
- remove extraneous line in `setup.py`\
- clean up style
=> refactor source

papermill/cli.py, requirements-dev.txt
Clean up in preparation for creating autodocs and increasing test coverage.
=> Clean up docstrings and style

papermill/tests/notebooks/s3/s3_in/s3-simple_notebook.ipynb, papermill/tests/test_cli.py
- try testing using click's test cli runner
=> add cli tests for click

papermill/tests/test_api.py, papermill/tests/test_cli.py, papermill/tests/test_execute.py, papermill/tests/test_parameterize.py
Nothing to see here, just some PEP8'ing.
=> PEP8 rolling through

papermill/api.py
- add docstrings
- rename parameter in `_fetch_notebook_data(nb_node)` for better code understanding
=> clean up api docstrings for use in autodocs

papermill/s3.py
fix assert to ensure it works (now gets: SyntaxWarning: assertion is always true, perhaps remove parentheses?)
=> Fix assertion in s3.py

.gitignore, papermill/execute.py
Hi, here I add this to let the user choose how to deal with execution result if I use it in an application, I can use variable to deal with the result, no need to read again from the output file. Thanks.
=> Let user choose how to deal with execution result.

papermill/execute.py, papermill/tests/test_execute.py
Solves https://github.com/nteract/papermill/issues/148
=> Added long translations for integer values above max and min scala Int

CHANGELOG.md, RELEASING.md
Solving https://github.com/nteract/papermill/issues/146
Not automated, but good starting place for our CHANGELOG
=> Added a changelog to papermill

CONTRIBUTING.md, DEVELOPMENT_GUIDE.md, README.md, papermill/execute.py, papermill/iorw.py, papermill/preprocess.py, papermill/tests/test_execute.py, papermill/tests/test_translators.py, papermill/translators.py
Moved translator functions into a registry pattern (functionality the same)
Moved translator tests + added more tests
Created docs on how to write develop aspects of the app (coupled with changes as a promotion of translators)
- Translators
- IO
- CLI
=> Translators

papermill/iorw.py, papermill/tests/test_iorw.py
=> Added Accept: application/json header to iorw.HttpHandler.read

.travis.yml
Ignore failures here -- testing a theory based on conversation with google cloud developer for failed package install
=> Testing changes to enable 3.7 builds

setup.py
- update author email
- correct to support markdown readme (pypa reference deployment https://github.com/pypa/sampleproject/blob/master/setup.py)
=> update setup for markdown description

README.md, docs/usage.rst
=> Docs: -r, -f, -y and -b parameters

papermill/tests/test_translators.py, papermill/translators.py
=> add julia translators

.gitignore, MANIFEST.in, README.md, binder/highlight_dates.ipynb, binder/process_highlight_dates.ipynb, binder/requirements.txt, docs/usage.rst
I was playing around with the papermill API to learn how it works, and I decided to write up a little example notebook to help myself learn. I thought it might be useful for others to learn how to use papermill as well, so here's a PR that:
1. Sets up a Binder folder so we can install some requirements needed for an example
2. Adds an example notebook that demonstrates a (sort-of) "real world" usecase for papermill, and highlights some of its functionality.
3. Updates binder links to point to this example.
Open to suggestions/comments/etc!
=> adding example for binder

papermill/api.py, papermill/tests/test_api.py
I noticed that a string isn't being properly populated w/ its corresponding value!
=> Adding the name to output string

papermill/iorw.py, papermill/tests/test_iorw.py
Fixes https://github.com/nteract/papermill/issues/264
=> Fixed yaml read warnings

papermill/execute.py, papermill/tests/notebooks/keyboard_interrupt.ipynb, papermill/tests/test_execute.py
=> Don't raise exceptions saved in notebooks when using --prepare-only

papermill/execute.py, papermill/tests/test_parameterize.py, papermill/tests/test_translators.py, papermill/translators.py
=> change parameterization to use kernel name and language defined in the notebook

papermill/execute.py, papermill/iorw.py, papermill/tests/notebooks/read_check.ipynb, papermill/tests/test_execute.py, papermill/tests/test_iorw.py, papermill/tests/test_utils.py, requirements.txt
Changed cwd option to not change input / output notebook paths.
Solves https://github.com/nteract/papermill/issues/268 and https://github.com/nteract/papermill/issues/273
=> Cwd improvements

papermill/exceptions.py, papermill/iorw.py
=> Catch missing APPDATA key

binder/requirements.txt, tox.ini
Now you'll know the binder link will work before merging :)
=> Added binder check to tox tests

README.md, binder/cli-simple/simple_input.ipynb, binder/cli-simple/simple_output.ipynb, binder/highlight_dates.ipynb, binder/process_highlight_dates.ipynb, binder/requirements.txt, docs/index.rst, docs/usage-collection.rst, docs/usage-display.rst, docs/usage-recording.rst, papermill/api.py, papermill/utils.py, requirements-azure.txt
Now that nteract-scrapbook==0.2.0 is released, we can officially deprecate these functions!
Final piece of https://github.com/nteract/papermill/issues/175
=> Deprecated record functionality

papermill/execute.py, papermill/tests/test_iorw.py
Should close #245, let me know if somethine else was needed
=> Log a warning if the input notebook doesn't have a parameters cell

papermill/exceptions.py, papermill/execute.py, papermill/parameterize.py, papermill/tests/test_parameterize.py
Work in progress for nteract/papermill#300
=> Add path interpolation using parameters and special keys

papermill/engines.py, papermill/preprocess.py, papermill/tests/test_iorw.py, requirements.txt
- Added preprocessor changes needed to support nbconvert 5.5 widgets support
=> This PR preps papermill for supporting new 5.5 changes

papermill/iorw.py, papermill/tests/test_iorw.py
Closes https://github.com/nteract/papermill/issues/243
=> Add string io source

docs/index.rst, docs/troubleshooting.rst
Create a troubleshoot section in the docs and create a first entry about NoSuchKernel error linked to conda environments #251
=> Troubleshoot kernel

papermill/iorw.py
I should update more often, this has been broken for a few months 😰
=> fix ADLHandler registration in papermill_io

docs/troubleshooting.rst
- fixes #382 missing conda kernel documentation
- better syntax highlighting
=> update conda kernels documentation

docs/usage-parameterize.rst, docs/usage-workflow.rst
- as per https://github.com/nteract/papermill/pull/384#discussion_r298270694
- add warning about inter-dependent parameters
- misc formatting & neutral language
- add some useful missing entries to Usage ToC
=> update params documentation

azure-pipelines.yml
Trying out PR builds with Azure as well!
=> Added unittests for windows and mac

CHANGELOG.md, docs/reference/papermill-cli.rst, docs/usage-cli.rst, docs/usage-execute.rst, papermill/cli.py, papermill/tests/test_cli.py
Changelog and doc updates for #409 
There's one open PR we could get in before release if #411 gets tests fixed soon.
=> Added release notes for papermill 1.1.0

papermill/s3.py
=> Add endpoint-url from env

docs/reference/papermill-cli.rst, docs/usage-cli.rst, papermill/cli.py, papermill/tests/test_cli.py
=> Fix spelling of not-report-mode to no-report-mode

papermill/tests/test_translators.py, papermill/translators.py, requirements-azure.txt
See PR https://github.com/nteract/papermill/pull/448 for prerequisites / install
=> Translator: F# (dotnet-fsharp)

papermill/abs.py, papermill/cli.py, papermill/engines.py, papermill/iorw.py, papermill/tests/test_abs.py, papermill/tests/test_cli.py, papermill/tests/test_execute.py, papermill/tests/test_gcs.py, papermill/tests/test_iorw.py, papermill/tests/test_translators.py, papermill/translators.py, papermill/utils.py, requirements-azure.txt, tox.ini
I've changed each method in abs.py to use the new versions of the functions. 
I have some issues I'd like to discuss however, the first being that with the v12.1.0, when you upload a blob that already exists in storage it will fail to upload, saying the blob already exists. I've also noticed that when you go to upload a blob that doesn't exist, it still says it failed because it exists, but it does make it to storage. I think [this issue on stack overflow](https://stackoverflow.com/questions/4897826/azure-storage-error-the-specified-blob-already-exists-but-it-doesnt) might be the reason - not sure though I have no investigated it
=> Update Azure blob storage to use azure-storage-blob v12.1.0

papermill/iorw.py, papermill/tests/test_hdfs.py, requirements-hdfs.txt, setup.py
Hi, I added a hdfs handler in for the IO sources. First time contributor to this repo. Hope it is a needed feature. :)
=> Hdfs support

docs/extending-entry-points.rst, docs/reference/papermill-workflow.rst, docs/reference/papermill.tests.rst, papermill/clientwrap.py, papermill/engines.py, papermill/tests/test_clientwrap.py, papermill/tests/test_engines.py, papermill/tests/test_execute.py, requirements.txt
Waiting for the first release of https://github.com/jupyter/nbclient (which is waiting on a minumum of these 2 prs to merge: https://github.com/jupyter/nbclient/pull/12 and https://github.com/jupyter/nbclient/pull/17)
=> Replace NBConvert with NBClient

papermill/cli.py, papermill/tests/test_cli.py, papermill/tests/test_hdfs.py, papermill/tests/test_iorw.py
To add `Try Except` for checking `DeadKernelException`, which is to catch OOM hence it will return **138**.
To fix issue #478
=> Add DeadKernelException to execute_notebook()

papermill/tests/test_translators.py, papermill/translators.py
Added Support for Powershell Translator.
Fixes #509 
Tests can be found at https://github.com/haresudhan/pwsh-papermill.
=> Powershell translator added.

papermill/tests/notebooks/systemexit.ipynb, papermill/tests/test_execute.py
=> add test for SystemExit

CONTRIBUTING.md
=> Cleanup of CoC in CONTRIBUTING.md

CODE_OF_CONDUCT.md, CONTRIBUTING.md, docs/extending-developing.rst
Closes #576 
- Add a code of conduct file for GitHub Insights Community Profile to recognize nteract coc
- Update links to nteract coc from master to main
=> Update code of conduct link and add explicit file

.readthedocs.yaml, MANIFEST.in, docs/conf.py, docs/requirements-doc.txt
- add config file for RTD
- pin doc dependencies
=> Update RTD build

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Add simple template for Bug & Feature
Add PR template :rabbit:
=> adding GitHub templates

papermill/__main__.py, papermill/cli.py, papermill/tests/notebooks/binder.ipynb, papermill/tests/test_cli.py, setup.py
Moving the main to special `__main__` file so it is recognised with package call
Resolves #607
=> make use `-m papermill` directly

.github/workflows/ci.yml, papermill/tests/test_cli.py, papermill/tests/test_iorw.py, tox.ini
Adding check for flake8 which is defined already in setup.cfg
Also fixing existing issues :rabbit:
=> CI: add flake8 + fixes

.github/workflows/ci.yml, setup.cfg, tox.ini
unify the confusion in setup.cfg and in tox file to use the same
=> flake8: unify tox & setup

papermill/iorw.py
- Fix incorrect indent spacing
=> fix indents

.github/workflows/ci.yml, setup.py, tox.ini
=> add 3.10 to ci and setup

docs/changelog.md
=> Prepare changelog for 2.3.4

.bumpversion.cfg, papermill/version.py
=> bump version to 2.3.4

.pre-commit-config.yaml, MANIFEST.in
This will automatically format the before each commit if you enable it in your local dev environment.
This can also be paired with Bot (need to be installed), which would commit formatting correction directly to each open PR.
See: https://pre-commit.ci
=> add pre-commit

.pre-commit-config.yaml
This enables updating python syntax for minimal 3.7
=> enable pyupgrade

docs/requirements.txt
Add nbformat for now to the docs dependencies
=> Add nbformat to docs deps

docs/requirements.txt
Add back the base requirements when building docs for RTD
=> Update deps for docs

.github/dependabot.yml
Recently, I got some vulnerability warnings.
=> add dependabot also for pip packages

docs/changelog.md
=> release notes for 2.6.0
